const express = require("express")
const cors = require("cors")
const dotenv = require("dotenv")
dotenv.config()
const mongoose = require("mongoose")
const routerApi = require("./routes/routes.api")
mongoose.connect(process.env.RestfulAPIDB).then(() => {console.log("Database connected")}).catch(() => {
 console.log("Failed to connect")
})
const app = express()
app.listen(process.env.PORT)
app.use(express.json())
app.use(cors())
app.use("/api", routerApi)